# -*- coding: utf-8 -*-
"""complex(27-11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17BuhEnwJFFcImlFORBO2MxOHJ2GmXuLy
"""

#perform addition of two complex numbers using class COMPLEX.
#COMPLEX has two class variables real_part and img_part.
#constructors assig values for the respective variables.
#create three objects c1 , c2 , c3.where is the result of adding c1  and c2


class Complex:
    def __init__(self, real, imag):
        self.r_p = real
        self.i_p = imag

    def display(self):
        print(f"{self.r_p} + {self.i_p}j")

    @classmethod
    def add_complex(cls, c1, c2):
        real_sum = c1.r_p + c2.r_p
        imag_sum = c1.i_p + c2.i_p
        return cls(real_sum, imag_sum)

if __name__ == "__main__":
  c1 = Complex(2, 3)
  c2 = Complex(1, 4)

  print("Complex Number 1:")
  c1.display()
  print("Complex Number 2:")
  c2.display()

  c3 = Complex.add_complex(c1, c2)

  print("Result after addition:")
  c3.display()