# -*- coding: utf-8 -*-
"""encrypt,decrypt(19-11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HiJM3-kRSenZFLHXv92yJeFiTSe9vjX
"""

def encrypt(text, shift):
    encrypted_text = ""
    for char in text:
        if char.isalpha():
            is_upper = char.isupper()
            shifted_char = chr((ord(char) - ord('A' if is_upper else 'a') + shift) % 26 + ord('A' if is_upper else 'a'))
            encrypted_text += shifted_char
        else:
            encrypted_text += char
    return encrypted_text

def decrypt(encrypted_text, shift):
    return encrypt(encrypted_text, -shift)
text_to_encrypt = "My name is Lohitha"
shift_value = 4

encrypted_text = encrypt(text_to_encrypt, shift_value)
print(f"Encrypted Text: {encrypted_text}")

decrypted_text = decrypt(encrypted_text, shift_value)
print(f"Decrypted Text: {decrypted_text}")

