# -*- coding: utf-8 -*-
"""hexagon area(19-11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yqHxY6vKRXAxWXqEt5HLDVoHI7m_Puun
"""

def hexagon_area(l):

  area = (3* (3**0.5 ))/2 *l **2

  return area
l=10

print('area of hexagon is' , hexagon_area(l))

def hexagon_area(l):

  area = (3* (3**0.5 ))/2 *l **2

  return area
l= 5

print('area of hexagon is' , hexagon_area(l))