# -*- coding: utf-8 -*-
"""largest element(19-11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ng_Bx9OJXNkBlrOCsjJV0c7_lW5sr8C1
"""

def largest(list):
    large= list[0]
    for i in list:
        if i>large:
            large=i
    return large

list=[3, 9, 7, 3, 6, 5, 7, 24, 6]
print("largest in ",list,"is")
print(largest(list))