# -*- coding: utf-8 -*-
"""oop lab 2 (20 -11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bqdoP95p436ld12aZ6xeJPPnz6BIqKCD
"""

#write a python program to create two empty classes , student and marks.now create some instances
#check whether they are instances of the said class or not.
#also check whether the said classes are subclasses of the built in object class or not

class Student:
    pass

class Marks:
    pass

student_instance = Student()
marks_instance = Marks()

is_student_instance = isinstance(student_instance, Student)
is_marks_instance = isinstance(marks_instance, Marks)

is_student_subclass = issubclass(Student, object)
is_marks_subclass = issubclass(Marks, object)

print(is_student_instance)
print(is_marks_instance)

print(is_student_subclass)
print(is_marks_subclass)

#create a python class called birthdayboy that takes two variables
# a string name and an integer age .dont forgot init function within birthdayboy.create a method called birthday that increases the value of age by 1
#once this class has been created,create an instance of a class then call birthday methods on that to increase its age and print the same

class birthdayboy:

  def __init__(self , name , age):
    self.name = name
    self.age = age

  def birthday(self):
    Age = self.age +1
    print(Age)

b= birthdayboy("lohi",20)
print(b.birthday())

#Define a class called song, it will show the lyrics of a song.its _init__ method should have two arguments
# self and lyrics.lyrics is a list.
#inside your class create a method called sing me a song that print each element of lyrics on his own line.Define a variable

class song:
  def __init__(self , lyrics):
    self.lyrics = lyrics

  def sing_me_a_song(self):
    for i in self.lyrics:
      print(i)


s = song(['May god bless you' , 'Have a sunshine on you' , 'Happy birthday to you...!'])
print(s.sing_me_a_song())

class Dog:
  def __init__(self , name , size , breed = "unknown" , dob = "unknown"):
    self.name = name
    self.size = size
    self.breed = breed
    self.dob = dob

  def bark(self):
    print("wolf")

  def get_name(self):
    print(self.name)

  def set_name(self , Name):
    self.name = Name
    print(self.name)

  def dog_years(self , cur_year):
    YOB = self.dob[6:]
    year = int(YOB)
    age = (cur_year - year)*7
    print(age)

D = Dog('snoopy' , 33 , 'Pug' ,"02/02/2022" )
print(D.bark())
print(D.get_name())
print(D.set_name("silky"))
print(D.dog_years(2023))