# -*- coding: utf-8 -*-
"""oop LAB 3(27-11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GZIL6hKyQC2i2vvBd03piNLtE68TfqBr
"""

class BMS:

  def display(self):
    self.college_name = 'BMSCE'
    print(self.college_name)

  def add(n1,n2):
    print(n1 +n2)

B1 = BMS()
B1.display()
BMS.add(10 , 20)

class Calculator:
  def __init__(self , version):
    self.version = version

  def display(self):
    print(self.version)
  def add(n1 ,n2):
    print(n1+n2)
    return n1+n2

def main():
    C1 = Calculator('version1')
    C1.display()
    Calculator.add(30, 45)

    C2 = Calculator('version2')
    C2.display()
    Calculator.add(45, 55)

if __name__ == "__main__":
    main()

class student:
  counter = 0

  def __init__(self , n,m):
    self.name = n
    self.marks = m
    student.counter +=1


  def display(self):
    print(self.name)
    print(self.marks)
  @classmethod
  def obj_count(cls):
    return cls.counter

if __name__ == "__main__":
  S1 = student('k' , 20)
  S1.display()
  S2 = student('k' , 21)
  S2.display()

  print(student.obj_count())