# -*- coding: utf-8 -*-
"""valid email(19 -11-23).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPRItzOzzeAhOFMusdP1DONPy7C4XpN7
"""

def is_valid_email(email_address):
    if '@' in email_address and email_address.count('@') == 1:
        username, domain = email_address.split('@')
        if username and domain:

            if username[0].isalnum():

                if len(email_address) <= 256:
                    return True
    return False

email = input("Enter an email address: ")
if is_valid_email(email):
    print(" valid email address.")
else:
    print('It is not a valid email address.')